version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8001:80
    links:
      - "mysql"
    volumes: 
      - ./:/var/www/html/
    networks: 
      - my_network

  mysql:
    image: mysql:5.7
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysql_app
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3301:3306
    volumes: 
      - .docker/database/:/var/lib/mysql/
    networks: 
      - my_network

networks:
  my_network: 
    external: 
      name: app-network